version: '3.5'
networks:
  backend:
volumes:
  mongo-volume:
services:
  ### MongoDB ##############################################
  mongo:
    build: ./Mongo
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      # - ./data:/data/db
      - mongo-volume:/data/db
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}'
      - 'MONGO_INITDB_DATABASE=${MONGO_DB_NAME}'
      - 'MONGO_DB_USER=${MONGO_DB_USER}'
      - 'MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}'
    networks:
      - backend
    restart: unless-stopped
  ### Example Nodejs #############################################
  express:
    build: ./Express
    ports:
      - 3011:3000
    networks:
      - backend
    environment:
      - 'MONGO_CONNECTION=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}'
      - 'MONGO_DB_USER=${MONGO_DB_USER}'
      - 'MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}'
      - 'MONGO_DB_HOST=${MONGO_DB_HOST}'
      - 'MONGO_PORT=${MONGO_PORT}'
      - 'MONGO_DB_NAME=${MONGO_DB_NAME}'
    restart: unless-stopped
